baseURL: "https://ExolvoD.io/"
languageCode: "en-us"
title: "Exolvo"
theme: "up-business-theme"
DefaultContentLanguage: "en"

params:
  description: "Bringing Software Engineering to ML Deployments."
  author: "Exolvo"
  dateFormat: "2006-01-02"
  favicon: "/img/fav.ico"
  showMenu: true
  showRSSButton: false
  fadeIn: true
  fadeInIndex: false
  customCSS: ["css/custom.css"]
  email: "admin@exolvo.io"

menu:
  main:
    - identifier: home
      name: Home
      url: "/"
      weight: 1
    - identifier: about
      name: About Us
      url: "/about/"
      weight: 2
    - identifier: products
      name: Products
      url: "/products/"
      weight: 3
  footer:
    - identifier: about
      name: About Us
      url: "/about/"
      weight: 1
    - identifier: contact
      name: Contact Us
      url: "/contact-form.html"
      weight: 2
      
social:
  - name: Email
    url: "/contact-form.html"

markup:
  goldmark:
    renderer:
      unsafe: true